### ISSUE TITLE
.ui-widget-overlay { z-index: 3000 !important; } ?

### ISSUE THREAD

**Issue by zmilan** [PANmedia/raptor-editor#163]
Hi,

Is there any reason why this overlay z-index is set to be so big and even more !important? I add raptor-editor into my application and because of this settings I cant use any of modal dialog that exist in raptor-editor (for example setup link options). 
I fix it for my project with removing this z-index, but I'm wonder is there any reason why its there and also if possible what issues I can have with removing it.

**Comment by deeknow** [comment]
@zmilan just wondering how you got on with the z-index issue, did you end up modifying your own z-indexes or the raptor-editor ones. Think we will close this issue unless its an ongoing problem for you

**Comment by zmilan** [comment]
Hi @deeknow , I was solve it with just commented out that line (27437) in raptor.js and raptor.min.js. I know that is not good practice, but I not found any other solution in that moment. From my point of view, if no one else complain of this, than this is issue with my specific project/need, so feel free to close this issue. Thanks for asking.

**Comment by deeknow** [comment]
Thanks so much for replying @zmilan - glad to hear you have a workaround. It's always quite tricky dealing with z-indexes when combining multiple projects together.

**Comment by zmilan** [comment]
@deeknow you are welcome. Yes, it can be tricky and specially when !important is in use. For my project need, this was enough good patch, but i suppose it will not be good for some other needs.

**Comment by deeknow** [comment]
Thanks @zmilan - closing for now
