### ISSUE TITLE
Funny spanish translation

### ISSUE THREAD

**Issue by compilando** [PANmedia/raptor-editor#165]
Better use this translation:

pasteDialogFormattedUnclean: "Formato sin limpiar",
pasteDialogTitle: "Pegar",

Current ("formato inmundo" and "Pasta") sounds fun and weird in spanish...

**Comment by deeknow** [comment]
Hey @compilando just wondering if you have had a chance to look at the contributors page linked to by @Petah above and if so have you submitted your details on the agreement page? If so can you please consider sending a pull request through for this translation so we can credit you as the source. Sorry I know its a small change to the translation but it would be much appreciated :+1:

**Comment by faceleg** [comment]
Love the meme

**Comment by deeknow** [comment]
believe original poster may have moved onto other projects. committed the translation update for him in the locales project: https://github.com/PANmedia/raptor-locales/commit/1a49202d2a9bcf0a3646c1be034a0726f582c687
