### ISSUE TITLE
Event needed for when the editor exists in the DOM

### ISSUE THREAD

**Issue by BOOKPATH** [PANmedia/raptor-editor#167]
Currently ready fires too early. I need to know when the editor is in the DOM and accessible.

Any chance of adding a new event, like 'complete', or 'finished', means everything is built and the editor is visible.

I need this as my textarea is display: none, raptor then sets the editor to display none as well (is there any way to change this behaviour?), but ready fires before it is in the DOM. I know that raptor sets display: none on the textarea itself, but I want it hidden as I'm displaying a message that the editor is loading.

**Comment by deeknow** [comment]
@BOOKPATH just checking to see how you got on with @Petah's example?

**Comment by deeknow** [comment]
closing as part of legacy support issue triage - can open a new task should this feature be still required by original poster, or others
