### ISSUE TITLE
Button for clearing one applied class

### ISSUE THREAD

**Issue by compilando** [PANmedia/raptor-editor#168]
Hello,

I want to implement a button to clear surrounding custom tag `<entidad>` for a user selected text. It's like de "toggle" function, but I want a separate button to clear only this previously applied class. 

Can you help me?

Thanks in advance.

**Comment by deeknow** [comment]
Hi @compilando just checking to see if you managed to implement the button functionality or if you require any additional support. As per @Petah's post above we would need some more info from you to investigate/respond.

**Comment by deeknow** [comment]
closing as part of legacy support issue triage - can open a new task should this feature be still required by original poster, or others
