### ISSUE TITLE
build process/documentation

### ISSUE THREAD

**Issue by agenteo** [PANmedia/raptor-editor#169]
Hi...

I was trying to extend raptor link js, but had problems building the library.

I am unsure what the -build prokect is... is it meant to generate what's in -editor?

Anyway, here's a few notes of how I had to adjust the build process. Still not able to see a generated js.

### Building process to customize link creation
* building process not matching their documentation https://github.com/PANmedia/raptor-build https://www.raptor-editor.com/documentation/tutorials/build-run-from-source
* run `git clone git@github.com:PANmedia/raptor-build.git`
* Had to manually install the npm packages at first.
```
eteotti:~/lab/rich_text_editor/raptor/raptor-build (master) |$ ./bin/build
~/lab/rich_text_editor/raptor/raptor-build ~/lab/rich_text_editor/raptor/raptor-build

module.js:340
throw err;
^
Error: Cannot find module 'lodash'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/Users/eteotti/lab/rich_text_editor/raptor/raptor-build/build/build.js:1:71)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
```

* then realized i need to run `npm install`
* also need to change permissions `chmod a+x bin/*`
* now the build script is failing with a node error:

```
$ ./bin/build
~/lab/rich_text_editor/raptor/raptor-build ~/lab/rich_text_editor/raptor/raptor-build
Skipping missing path: raptor-common
Skipping missing path: raptor-locales
Skipping missing path: raptor-dependencies
Skipping missing path: raptor-editor
Skipping missing path: raptor-file-manager
Skipping missing path: raptor-image-editor
Skipping missing path: raptor-premium
Skipping missing path: raptor-section
Skipping missing path: raptor-themes
[Error: stderr maxBuffer exceeded.]
```

* tried to `sudo` that and got a different error:
```
eteotti:~/lab/rich_text_editor/raptor/raptor-build (master) |$ sudo ./bin/build --trace
~/lab/rich_text_editor/raptor/raptor-build ~/lab/rich_text_editor/raptor/raptor-build
Skipping missing path: raptor-common
Skipping missing path: raptor-locales
Skipping missing path: raptor-dependencies
Skipping missing path: raptor-editor
Skipping missing path: raptor-file-manager
Skipping missing path: raptor-image-editor
Skipping missing path: raptor-premium
Skipping missing path: raptor-section
Skipping missing path: raptor-themes
{ [Error: Command failed: LoadError: cannot load such file -- susy
  Use --trace for backtrace.
  ] killed: false, code: 1, signal: null }
  ~/lab/rich_text_editor/raptor/raptor-build
```

Even if the gems were installed via RVM, and I ensured we were on the correct rvm and gemset... since we are running the script as sudo it has not access to the same gems...
Installed sass and compass as sudo.
* `sudo gem install sass`
* `sudo gem install compass`
* `sudo gem install susy` (not even in the dependency list but erroring)

Finally... the raptor.js file is generated... and it doesn't contain any JS...

```
eteotti:~/lab/rich_text_editor/raptor (master) |$ cat raptor-build/temp/raptor.min.js
document.write('<style type="text/css"></style>');eteotti:~/lab/rich_text_editor/raptor (master) |$ cat raptor-build/temp/raptor.js
(function(){})();document.write('<style type="text/css">\n\
\n\
/*# sourceMappingURL=raptor.css.map */\n\
```

This is blocking our efforts to extend raptor.

Thanks

ps
Same ticket opened on -build project. Feel free to close the one you're not following up.

**Comment by deeknow** [comment]
Hi @agenteo I've recently built the editor myself using the repos online at the moment which I assume do contain a fix @Petah must have pushed some time after the post above. Can you confirm that you were eventually able to complete a build without seeing the REQUEST_URI error? If so we can close this ticket.

**Comment by deeknow** [comment]
closing this issue - build process seems to be fine now - can open another issue in future should there be any new specific build problems raised
