### ISSUE TITLE
Errors in console (Chrome)

### ISSUE THREAD

**Issue by oxhey** [PANmedia/raptor-editor#176]
'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach). - raptor.js:31547

Discontiguous selection is not supported. - raptor.js:34260

Im using the 0 dependencies preset

**Comment by Petah** [comment]
Its just an unsuppressible error from Chrome/Rangy while doing feature detection. It should not cause any issues.
